; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_h753zi]
platform = ststm32
board = devebox_h743vitx
framework = arduino
board_build.f_cpu = 640000000L

build_flags =
  ; Generic file management
  -I include
  ; STM configuration
  -D USE_HAL_SPI_REGISTER_CALLBACKS=1
  -D PIO_FRAMEWORK_ARDUINO_NANOLIB_FLOAT_PRINTF
  ; LVGL Stuff
  -D LV_CONF_PATH='"${PROJECT_DIR}/include/lv_conf.h"'


lib_deps = 
  SPI @ 1.1.0
  lvgl/lvgl @ 9.5.0
  arduino-libraries/Ethernet @ 2.0.2
  stm32duino/STM32duino RTC @ 1.8.0

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
